# Generated by Django 4.1.2 on 2022-11-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_delete_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='docter',
            name='pic',
            field=models.FileField(default='avatar.png', upload_to='user profile'),
        ),
    ]
