# Generated by Django 4.1.2 on 2022-10-18 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_docter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docter',
            old_name='gender',
            new_name='specilist',
        ),
    ]
