# Generated by Django 4.1.2 on 2022-11-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_docter_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
    ]
