# Generated by Django 4.0.6 on 2022-11-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
            ],
        ),
    ]
